### ISSUE TITLE
Allow specifying password and database number

### ISSUE THREAD

**Issue by rchavik** [kamisama/php-resque-ex#10]
When using this with CakeResque, I needed to set password and database number.

After a *very* quick look, this feature does not seem available.  So, at the moment, I hardcoded the `$this->auth(password)` and `$this->select(n)` in `RedisApi::establishConnection()` directly.

Would appreciate if this can be configurable when used together with CakeResque`.

**Comment by kamisama** [comment]
Added in **1.3.0**
